### ISSUE TITLE
setting labels based on who responds

### ISSUE THREAD

**Issue by jwhett** [jwhett/labeljay#6]

**Comment by jwhett** [comment]
this comment should replace the current set of labels with `Waiting on user feedback`

**Comment by jwhett** [comment]
jk it should work this time? :eyes:

**Comment by jwhett** [comment]
![boom baby](https://media.giphy.com/media/12yB3XoYboAkjm/giphy.gif)

**Comment by tjajt** [comment]
This looks quite neat--eggxellent work!
